import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google'
import Navbar from "@/components/custom/navbar";
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip";

const font = Poppins({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "FlowPro",
  description: "Generated by vaxad",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased min-h-screen`}>
        <TooltipProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster />
            <Navbar />
            {children}
          </ThemeProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
